# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02b636928a1d1ade637bc711edc16fe8c8600f7fa7728f3159b8bb6e1a50f68ee1b4eb7126c6f2294e2970dd07d30fc425223b9550900bdf766773be33083bb1

test:
  secret_key_base: ee578754752e1974b3d0edd771dedad097eaa1a84c424896737c7000ed5cf37b2328344b955301832ceecfb96af31db7350837333052a16bea63e0a0c6bdcde9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
